<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerusahaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id_perusahaan' => 1,
                'id_admin' => 1,
                'nama' => 'PT. Maju Mundur',
                'alamat' => 'Jl. Raya No. 1',
                'no_telepon' => '08123456789',
                'email' => 'qNw0s@example.com',
                'website' => 'www.maju-mundur.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 2,
                'id_admin' => 1,
                'nama' => 'PT. Global Media Nusantara',
                'alamat' => 'Jl. Gatot Subroto Kav. 35-36, Jakarta Selatan',
                'no_telepon' => '0218765432',
                'email' => 'contact@globalmedia.co.id',
                'website' => 'www.globalmedia.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 3,
                'id_admin' => 2,
                'nama' => 'PT. Indofood Sukses Makmur',
                'alamat' => 'Sudirman Plaza, Indofood Tower, Jl. Jend. Sudirman Kav. 76-78, Jakarta',
                'no_telepon' => '02157958822',
                'email' => 'corporate.secretary@indofood.co.id',
                'website' => 'www.indofood.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 4,
                'id_admin' => 2,
                'nama' => 'PT. Bank Central Asia Tbk',
                'alamat' => 'Menara BCA, Grand Indonesia, Jl. M.H. Thamrin No. 1, Jakarta',
                'no_telepon' => '02123588000',
                'email' => 'halo.bca@bca.co.id',
                'website' => 'www.bca.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 5,
                'id_admin' => 3,
                'nama' => 'PT. Telkom Indonesia Tbk',
                'alamat' => 'Jl. Japati No. 1, Bandung',
                'no_telepon' => '02214526455',
                'email' => 'corporate@telkom.co.id',
                'website' => 'www.telkom.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 6,
                'id_admin' => 3,
                'nama' => 'PT. Astra International Tbk',
                'alamat' => 'Jl. Gaya Motor Raya No. 8, Sunter II, Jakarta',
                'no_telepon' => '02165066555',
                'email' => 'info@ai.astra.co.id',
                'website' => 'www.astra.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 7,
                'id_admin' => 4,
                'nama' => 'PT. Unilever Indonesia Tbk',
                'alamat' => 'Graha Unilever, Green Office Park Kav. 3, BSD City, Tangerang',
                'no_telepon' => '02180827000',
                'email' => 'id.relations@unilever.com',
                'website' => 'www.unilever.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 8,
                'id_admin' => 4,
                'nama' => 'PT. Gojek Indonesia',
                'alamat' => 'Pasaraya Blok M, Gedung B, Jl. Sultan Hasanudin, Jakarta Selatan',
                'no_telepon' => '02150251110',
                'email' => 'info@gojek.com',
                'website' => 'www.gojek.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 9,
                'id_admin' => 5,
                'nama' => 'PT. Tokopedia',
                'alamat' => 'Tokopedia Tower, Ciputra World 2, Jakarta Selatan',
                'no_telepon' => '02180625960',
                'email' => 'pr@tokopedia.com',
                'website' => 'www.tokopedia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 10,
                'id_admin' => 5,
                'nama' => 'PT. Bukalapak.com',
                'alamat' => 'Metropolitan Tower, Jl. R.A. Kartini Kav. 14, Jakarta',
                'no_telepon' => '02150963333',
                'email' => 'corcom@bukalapak.com',
                'website' => 'www.bukalapak.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 11,
                'id_admin' => 6,
                'nama' => 'PT. Bank Rakyat Indonesia Tbk',
                'alamat' => 'Gedung BRI, Jl. Jenderal Sudirman Kav. 44-46, Jakarta',
                'no_telepon' => '02125751966',
                'email' => 'callbri@bri.co.id',
                'website' => 'www.bri.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 12,
                'id_admin' => 6,
                'nama' => 'PT. Bank Mandiri Tbk',
                'alamat' => 'Plaza Mandiri, Jl. Jenderal Gatot Subroto Kav. 36-38, Jakarta',
                'no_telepon' => '0215245065',
                'email' => 'corporate.secretary@bankmandiri.co.id',
                'website' => 'www.bankmandiri.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 13,
                'id_admin' => 7,
                'nama' => 'PT. Pertamina',
                'alamat' => 'Jl. Medan Merdeka Timur No. 1A, Jakarta',
                'no_telepon' => '02138158075',
                'email' => 'pcc@pertamina.com',
                'website' => 'www.pertamina.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 14,
                'id_admin' => 7,
                'nama' => 'PT. Garuda Indonesia Tbk',
                'alamat' => 'Garuda Management Building, Soekarno-Hatta Airport, Tangerang',
                'no_telepon' => '02123519999',
                'email' => 'corporate@garuda-indonesia.com',
                'website' => 'www.garuda-indonesia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 15,
                'id_admin' => 8,
                'nama' => 'PT. Kalbe Farma Tbk',
                'alamat' => 'Jl. Let. Jend. Suprapto Kav. 4, Jakarta',
                'no_telepon' => '0214287388',
                'email' => 'info@kalbe.co.id',
                'website' => 'www.kalbe.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 16,
                'id_admin' => 8,
                'nama' => 'PT. Adaro Energy Tbk',
                'alamat' => 'Menara Karya, Jl. H.R. Rasuna Said Blok X-5, Kav. 1-2, Jakarta',
                'no_telepon' => '02125538000',
                'email' => 'investor.relations@adaro.com',
                'website' => 'www.adaro.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 17,
                'id_admin' => 9,
                'nama' => 'PT. XL Axiata Tbk',
                'alamat' => 'XL Axiata Tower, Jl. H.R. Rasuna Said X-5 Kav. 11-12, Jakarta',
                'no_telepon' => '02156542222',
                'email' => 'corpsec@xl.co.id',
                'website' => 'www.xl.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 18,
                'id_admin' => 9,
                'nama' => 'PT. Indosat Tbk',
                'alamat' => 'Jl. Medan Merdeka Barat No. 21, Jakarta',
                'no_telepon' => '0230003001',
                'email' => 'corporate.secretary@indosatooredoo.com',
                'website' => 'www.indosatooredoo.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 19,
                'id_admin' => 10,
                'nama' => 'PT. Semen Indonesia Tbk',
                'alamat' => 'Gedung Utama Semen Indonesia, Jl. Veteran, Gresik',
                'no_telepon' => '0313981732',
                'email' => 'info@semenindonesia.com',
                'website' => 'www.semenindonesia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 20,
                'id_admin' => 10,
                'nama' => 'PT. United Tractors Tbk',
                'alamat' => 'Jl. Raya Bekasi Km. 22, Jakarta',
                'no_telepon' => '02124601608',
                'email' => 'ir@unitedtractors.com',
                'website' => 'www.unitedtractors.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 21,
                'id_admin' => 1,
                'nama' => 'PT. Mayora Indah Tbk',
                'alamat' => 'Gedung Mayora, Jl. Tomang Raya No. 21-23, Jakarta',
                'no_telepon' => '02125508888',
                'email' => 'corsec@mayora.co.id',
                'website' => 'www.mayora.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 22,
                'id_admin' => 2,
                'nama' => 'PT. Indomarco Prismatama (Indomaret)',
                'alamat' => 'Jl. Ancol Barat I/9-10, Jakarta',
                'no_telepon' => '02165834800',
                'email' => 'customer.service@indomaret.co.id',
                'website' => 'www.indomaret.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 23,
                'id_admin' => 3,
                'nama' => 'PT. Sumber Alfaria Trijaya Tbk (Alfamart)',
                'alamat' => 'Alfa Tower, Jl. Jalur Sutera Barat Kav. 9, Tangerang',
                'no_telepon' => '02180821555',
                'email' => 'info@alfamart.co.id',
                'website' => 'www.alfamart.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 24,
                'id_admin' => 4,
                'nama' => 'PT. Indah Kiat Pulp & Paper Tbk',
                'alamat' => 'Sinar Mas Land Plaza, Jl. MH. Thamrin No. 51, Jakarta',
                'no_telepon' => '02131930134',
                'email' => 'investor_relations@app.co.id',
                'website' => 'www.ikpp.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 25,
                'id_admin' => 5,
                'nama' => 'PT. BNI Life Insurance',
                'alamat' => 'Centennial Tower Lt. 9, Jl. Jend. Gatot Subroto Kav. 24-25, Jakarta',
                'no_telepon' => '02129461010',
                'email' => 'customerservice@bni-life.co.id',
                'website' => 'www.bni-life.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 26,
                'id_admin' => 6,
                'nama' => 'PT. Djarum',
                'alamat' => 'Jl. A. Yani No. 28, Kudus',
                'no_telepon' => '0291431901',
                'email' => 'corporate@djarum.com',
                'website' => 'www.djarum.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 27,
                'id_admin' => 7,
                'nama' => 'PT. Lion Air',
                'alamat' => 'Lion Air Tower, Jl. Gajah Mada No. 7, Jakarta',
                'no_telepon' => '0215747777',
                'email' => 'publicrelations@lionair.co.id',
                'website' => 'www.lionair.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 28,
                'id_admin' => 8,
                'nama' => 'PT. Astra Otoparts Tbk',
                'alamat' => 'Jl. Raya Pegangsaan Dua Km. 2.2, Jakarta',
                'no_telepon' => '02146019061',
                'email' => 'corporate.communication@component.astra.co.id',
                'website' => 'www.astra-otoparts.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 29,
                'id_admin' => 9,
                'nama' => 'PT. Trans Retail Indonesia (Transmart Carrefour)',
                'alamat' => 'Jl. H.R. Rasuna Said Kav. B7-A, Jakarta',
                'no_telepon' => '02129109999',
                'email' => 'customer.service@transretail.co.id',
                'website' => 'www.transmart.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 30,
                'id_admin' => 10,
                'nama' => 'PT. Kompas Gramedia',
                'alamat' => 'Menara Kompas Gramedia, Jl. Palmerah Selatan No. 22-28, Jakarta',
                'no_telepon' => '0215347710',
                'email' => 'publicrelations@kompasgramedia.com',
                'website' => 'www.kompasgramedia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 31,
                'id_admin' => 1,
                'nama' => 'PT. Lippo Karawaci Tbk',
                'alamat' => 'Menara Matahari, Jl. Boulevard Palem Raya No. 7, Tangerang',
                'no_telepon' => '02155788888',
                'email' => 'corsec@lippokarawaci.co.id',
                'website' => 'www.lippokarawaci.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 32,
                'id_admin' => 2,
                'nama' => 'PT. Ciputra Development Tbk',
                'alamat' => 'Ciputra World 1, DBS Bank Tower Lt. 39, Jakarta',
                'no_telepon' => '02129885858',
                'email' => 'investor@ciputra.com',
                'website' => 'www.ciputradevelopment.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 33,
                'id_admin' => 3,
                'nama' => 'PT. Sido Muncul Tbk',
                'alamat' => 'Office Sido Muncul, Gedung Menara Suara Merdeka, Semarang',
                'no_telepon' => '0248307979',
                'email' => 'info@sidomuncul.co.id',
                'website' => 'www.sidomuncul.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 34,
                'id_admin' => 4,
                'nama' => 'PT. Tiket.com',
                'alamat' => 'Wisma 77 Tower 2, Jl. Letjen. S. Parman Kav. 77, Jakarta',
                'no_telepon' => '02158204100',
                'email' => 'cs@tiket.com',
                'website' => 'www.tiket.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 35,
                'id_admin' => 5,
                'nama' => 'PT. Shopee Indonesia',
                'alamat' => 'Wisma 77 Tower 2, Jl. Letjen. S. Parman Kav. 77, Jakarta',
                'no_telepon' => '02129490110',
                'email' => 'support@shopee.co.id',
                'website' => 'www.shopee.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 36,
                'id_admin' => 6,
                'nama' => 'PT. Lazada Indonesia',
                'alamat' => 'Menara Palma, Jl. HR Rasuna Said Blok X2 Kav. 6, Jakarta',
                'no_telepon' => '02180648888',
                'email' => 'customer.service@lazada.co.id',
                'website' => 'www.lazada.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 37,
                'id_admin' => 7,
                'nama' => 'PT. Maybank Indonesia Tbk',
                'alamat' => 'Sentral Senayan III, Jl. Asia Afrika No. 8, Jakarta',
                'no_telepon' => '0221500611',
                'email' => 'customercare@maybank.co.id',
                'website' => 'www.maybank.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 38,
                'id_admin' => 8,
                'nama' => 'PT. CIMB Niaga Tbk',
                'alamat' => 'Menara CIMB Niaga, Jl. M.H. Thamrin No. 26, Jakarta',
                'no_telepon' => '02162886000',
                'email' => 'corporatesecretary@cimbniaga.co.id',
                'website' => 'www.cimbniaga.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 39,
                'id_admin' => 9,
                'nama' => 'PT. Bank Permata Tbk',
                'alamat' => 'Gedung WTC II, Jl. Jend. Sudirman Kav. 29-31, Jakarta',
                'no_telepon' => '0215237788',
                'email' => 'corporate.affairs@permatabank.co.id',
                'website' => 'www.permatabank.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 40,
                'id_admin' => 10,
                'nama' => 'PT. Bank OCBC NISP Tbk',
                'alamat' => 'OCBC NISP Tower, Jl. Prof. Dr. Satrio Kav. 25, Jakarta',
                'no_telepon' => '02125533888',
                'email' => 'callcenter@ocbcnisp.com',
                'website' => 'www.ocbcnisp.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 41,
                'id_admin' => 1,
                'nama' => 'PT. Biofarma',
                'alamat' => 'Jl. Pasteur No. 28, Bandung',
                'no_telepon' => '0222033755',
                'email' => 'info@biofarma.co.id',
                'website' => 'www.biofarma.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 42,
                'id_admin' => 2,
                'nama' => 'PT. Kimia Farma Tbk',
                'alamat' => 'Jl. Veteran No. 9, Jakarta',
                'no_telepon' => '0213847709',
                'email' => 'info@kimiafarma.co.id',
                'website' => 'www.kimiafarma.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 43,
                'id_admin' => 3,
                'nama' => 'PT. Bluebird Tbk',
                'alamat' => 'Jl. Mampang Prapatan Raya No. 60, Jakarta',
                'no_telepon' => '0217941234',
                'email' => 'customercare@bluebirdgroup.com',
                'website' => 'www.bluebirdgroup.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 44,
                'id_admin' => 4,
                'nama' => 'PT. Kereta Api Indonesia',
                'alamat' => 'Jl. Perintis Kemerdekaan No. 3, Bandung',
                'no_telepon' => '0224230031',
                'email' => 'customer.service@kai.id',
                'website' => 'www.kai.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 45,
                'id_admin' => 5,
                'nama' => 'PT. Pupuk Indonesia',
                'alamat' => 'Jl. Taman Anggrek Kemanggisan Jaya, Jakarta',
                'no_telepon' => '02153650145',
                'email' => 'info@pupuk-indonesia.com',
                'website' => 'www.pupuk-indonesia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 46,
                'id_admin' => 6,
                'nama' => 'PT. Pegadaian',
                'alamat' => 'Jl. Kramat Raya No. 162, Jakarta',
                'no_telepon' => '0213155550',
                'email' => 'customer.care@pegadaian.co.id',
                'website' => 'www.pegadaian.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 47,
                'id_admin' => 7,
                'nama' => 'PT. Pos Indonesia',
                'alamat' => 'Jl. Cilaki No. 73, Bandung',
                'no_telepon' => '0224233333',
                'email' => 'halo.pos@posindonesia.co.id',
                'website' => 'www.posindonesia.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 48,
                'id_admin' => 8,
                'nama' => 'PT. Taspen',
                'alamat' => 'Jl. Letjen Suprapto No. 45, Jakarta',
                'no_telepon' => '0214203805',
                'email' => 'taspen@taspen.co.id',
                'website' => 'www.taspen.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 49,
                'id_admin' => 9,
                'nama' => 'PT. Jasa Marga Tbk',
                'alamat' => 'Plaza Tol Taman Mini Indonesia Indah, Jakarta',
                'no_telepon' => '02184591666',
                'email' => 'jasamarga@jasamarga.co.id',
                'website' => 'www.jasamarga.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 50,
                'id_admin' => 10,
                'nama' => 'PT. Angkasa Pura I',
                'alamat' => 'Kota Baru Bandar Kemayoran Blok B12 Kav. 2, Jakarta',
                'no_telepon' => '02165411961',
                'email' => 'humas@ap1.co.id',
                'website' => 'www.ap1.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 51,
                'id_admin' => 1,
                'nama' => 'PT. Angkasa Pura II',
                'alamat' => 'Soekarno-Hatta International Airport, Tangerang',
                'no_telepon' => '02155912049',
                'email' => 'contact.center@angkasapura2.co.id',
                'website' => 'www.angkasapura2.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 52,
                'id_admin' => 2,
                'nama' => 'PT. PLN',
                'alamat' => 'Jl. Trunojoyo Blok M-I No. 135, Jakarta',
                'no_telepon' => '02123560123',
                'email' => 'pln123@pln.co.id',
                'website' => 'www.pln.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 53,
                'id_admin' => 3,
                'nama' => 'PT. Toyota Astra Motor',
                'alamat' => 'Jl. Gaya Motor Selatan No. 5, Jakarta',
                'no_telepon' => '02165158000',
                'email' => 'customer.relation@toyota.astra.co.id',
                'website' => 'www.toyota.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 54,
                'id_admin' => 4,
                'nama' => 'PT. Honda Prospect Motor',
                'alamat' => 'Jl. Gaya Motor I, Jakarta',
                'no_telepon' => '02165156655',
                'email' => 'cr@honda-indonesia.com',
                'website' => 'www.honda-indonesia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 55,
                'id_admin' => 5,
                'nama' => 'PT. Suzuki Indomobil Motor',
                'alamat' => 'Jl. Raya Bekasi Km. 19, Jakarta',
                'no_telepon' => '02148898042',
                'email' => 'customercare@suzuki.co.id',
                'website' => 'www.suzuki.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 56,
                'id_admin' => 6,
                'nama' => 'PT. Daihatsu Astra',
                'alamat' => 'Jl. Gaya Motor III No. 5, Jakarta',
                'no_telepon' => '02165318888',
                'email' => 'customerservice@daihatsu.astra.co.id',
                'website' => 'www.daihatsu.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 57,
                'id_admin' => 7,
                'nama' => 'PT. Samsung Electronics Indonesia',
                'alamat' => 'Cikarang Industrial Estate, Bekasi',
                'no_telepon' => '02189837114',
                'email' => 'cs.id@samsung.com',
                'website' => 'www.samsung.com/id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 58,
                'id_admin' => 8,
                'nama' => 'PT. LG Electronics Indonesia',
                'alamat' => 'Jl. Jend. S. Parman Kav. 77, Jakarta',
                'no_telepon' => '0215501010',
                'email' => 'lgcare.id@lge.com',
                'website' => 'www.lg.com/id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 59,
                'id_admin' => 9,
                'nama' => 'PT. Panasonic Gobel Indonesia',
                'alamat' => 'Jl. Dewi Sartika No. 14, Jakarta',
                'no_telepon' => '0218015710',
                'email' => 'customer.care@id.panasonic.com',
                'website' => 'www.panasonic.com/id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 60,
                'id_admin' => 10,
                'nama' => 'PT. Sharp Electronics Indonesia',
                'alamat' => 'Jl. Swadaya IV, Jakarta',
                'no_telepon' => '0218650971',
                'email' => 'seid-cs@sharp-indonesia.com',
                'website' => 'www.sharp-indonesia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 61,
                'id_admin' => 1,
                'nama' => 'PT. Prudential Life Assurance',
                'alamat' => 'Prudential Tower, Jl. Jend. Sudirman Kav. 79, Jakarta',
                'no_telepon' => '02129958888',
                'email' => 'customer.service@prudential.co.id',
                'website' => 'www.prudential.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 62,
                'id_admin' => 2,
                'nama' => 'PT. Manulife Indonesia',
                'alamat' => 'Sampoerna Strategic Square, Jakarta',
                'no_telepon' => '0215804000',
                'email' => 'customerserviceid@manulife.com',
                'website' => 'www.manulife.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 63,
                'id_admin' => 3,
                'nama' => 'PT. AIA Financial',
                'alamat' => 'AIA Central, Jl. Jend. Sudirman Kav. 48A, Jakarta',
                'no_telepon' => '02154991500',
                'email' => 'id.customer@aia.com',
                'website' => 'www.aia-financial.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 64,
                'id_admin' => 4,
                'nama' => 'PT. Allianz Life Indonesia',
                'alamat' => 'Allianz Tower, Jl. HR Rasuna Said, Jakarta',
                'no_telepon' => '0212926999',
                'email' => 'contactus@allianz.co.id',
                'website' => 'www.allianz.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 65,
                'id_admin' => 5,
                'nama' => 'PT. Traveloka Indonesia',
                'alamat' => 'Wisma 77 Tower 2, Jakarta',
                'no_telepon' => '02127508800',
                'email' => 'cs@traveloka.com',
                'website' => 'www.traveloka.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 66,
                'id_admin' => 6,
                'nama' => 'PT. Bukit Asam Tbk',
                'alamat' => 'Jl. Parigi No. 1, Tanjung Enim',
                'no_telepon' => '0218507070',
                'email' => 'corsec@bukitasam.co.id',
                'website' => 'www.ptba.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 67,
                'id_admin' => 7,
                'nama' => 'PT. Vale Indonesia Tbk',
                'alamat' => 'The Energy Building, Jakarta',
                'no_telepon' => '0215249000',
                'email' => 'pti.communications@vale.com',
                'website' => 'www.vale.com/indonesia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 68,
                'id_admin' => 8,
                'nama' => 'PT. Freeport Indonesia',
                'alamat' => 'Plaza 89, Jl. H.R. Rasuna Said Kav. X-7 No. 6, Jakarta',
                'no_telepon' => '02125504000',
                'email' => 'info@freeport.com',
                'website' => 'www.ptfi.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 69,
                'id_admin' => 9,
                'nama' => 'PT. Bank BTPN Tbk',
                'alamat' => 'Menara BTPN, Jakarta',
                'no_telepon' => '02130026200',
                'email' => 'corporate.communications@btpn.com',
                'website' => 'www.btpn.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 70,
                'id_admin' => 10,
                'nama' => 'PT. Bank Danamon Indonesia Tbk',
                'alamat' => 'Menara Bank Danamon, Jakarta',
                'no_telepon' => '0215799999',
                'email' => 'corporate.communication@danamon.co.id',
                'website' => 'www.danamon.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 71,
                'id_admin' => 1,
                'nama' => 'PT. Nippon Indosari Corpindo Tbk (Sari Roti)',
                'alamat' => 'Kawasan Industri MM2100, Bekasi',
                'no_telepon' => '02189844959',
                'email' => 'customer.service@sariroti.com',
                'website' => 'www.sariroti.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 72,
                'id_admin' => 2,
                'nama' => 'PT. Mustika Ratu Tbk',
                'alamat' => 'Jl. Raya Bogor Km. 26,4, Jakarta',
                'no_telepon' => '0218710906',
                'email' => 'info@mustika-ratu.co.id',
                'website' => 'www.mustika-ratu.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 73,
                'id_admin' => 3,
                'nama' => 'PT. Mitra Adiperkasa Tbk',
                'alamat' => 'Wisma 46 Kota BNI, Jakarta',
                'no_telepon' => '0215701888',
                'email' => 'corporate@map.co.id',
                'website' => 'www.map.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 74,
                'id_admin' => 4,
                'nama' => 'PT. Matahari Department Store Tbk',
                'alamat' => 'Menara Matahari, Tangerang',
                'no_telepon' => '02155470555',
                'email' => 'ir@matahari.co.id',
                'website' => 'www.matahari.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 75,
                'id_admin' => 5,
                'nama' => 'PT. Ramayana Lestari Sentosa Tbk',
                'alamat' => 'Jl. K.H. Wahid Hasyim No. 220 A-B, Jakarta',
                'no_telepon' => '0213102888',
                'email' => 'corporate@ramayana.co.id',
                'website' => 'www.ramayana.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 76,
                'id_admin' => 6,
                'nama' => 'PT. Erajaya Swasembada Tbk',
                'alamat' => 'Jl. Gedong Panjang No. 29-31, Jakarta',
                'no_telepon' => '0216515588',
                'email' => 'investor.relation@erajaya.com',
                'website' => 'www.erajaya.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 77,
                'id_admin' => 7,
                'nama' => 'PT. MAP Aktif Adiperkasa Tbk',
                'alamat' => 'Sahid Sudirman Center Lt. 29, Jakarta',
                'no_telepon' => '0218064 3777',
                'email' => 'corpsec@mapactive.id',
                'website' => 'www.mapactive.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 78,
                'id_admin' => 8,
                'nama' => 'PT. Midi Utama Indonesia Tbk (Alfamidi)',
                'alamat' => 'Gedung Alfa Tower, BSD City, Tangerang',
                'no_telepon' => '02180821555',
                'email' => 'info@alfamidiku.com',
                'website' => 'www.alfamidiku.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 79,
                'id_admin' => 9,
                'nama' => 'PT. Fast Food Indonesia Tbk (KFC)',
                'alamat' => 'Jl. M.T. Haryono Kav. 7, Jakarta',
                'no_telepon' => '0218307000',
                'email' => 'contact.us@kfcindonesia.com',
                'website' => 'www.kfcindonesia.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 80,
                'id_admin' => 10,
                'nama' => 'PT. Sinar Mas Agro Resources and Technology Tbk',
                'alamat' => 'Plaza BII Tower II, Jakarta',
                'no_telepon' => '0215033888',
                'email' => 'investor@smart-tbk.com',
                'website' => 'www.smart-tbk.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 81,
                'id_admin' => 1,
                'nama' => 'PT. Wings Group Indonesia',
                'alamat' => 'Jl. Tipar Cakung Kav. F 5-7, Jakarta',
                'no_telepon' => '0214600086',
                'email' => 'info@wings.co.id',
                'website' => 'www.wingscorp.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 82,
                'id_admin' => 2,
                'nama' => 'PT. Nutrifood Indonesia',
                'alamat' => 'Jl. Rawabali II No. 3, Jakarta',
                'no_telepon' => '0214603020',
                'email' => 'customerservice@nutrifood.co.id',
                'website' => 'www.nutrifood.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 83,
                'id_admin' => 3,
                'nama' => 'PT. Kino Indonesia Tbk',
                'alamat' => 'Kino Tower, Jakarta',
                'no_telepon' => '02180508888',
                'email' => 'info@kino.co.id',
                'website' => 'www.kino.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 84,
                'id_admin' => 4,
                'nama' => 'PT. Tempo Scan Pacific Tbk',
                'alamat' => 'Tempo Scan Tower, Jakarta',
                'no_telepon' => '0221323567',
                'email' => 'info@thetempogroup.com',
                'website' => 'www.thetempogroup.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 85,
                'id_admin' => 5,
                'nama' => 'PT. Bunda Medik',
                'alamat' => 'Jl. Teuku Cik Ditiro No. 28, Jakarta',
                'no_telepon' => '0213908671',
                'email' => 'info@bundamedik.com',
                'website' => 'www.bundamedik.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 86,
                'id_admin' => 6,
                'nama' => 'PT. Siloam International Hospitals Tbk',
                'alamat' => 'Jl. Boulevard Gajah Mada No. 2096, Lippo Karawaci',
                'no_telepon' => '02155800000',
                'email' => 'customercare@siloamhospitals.com',
                'website' => 'www.siloamhospitals.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 87,
                'id_admin' => 7,
                'nama' => 'PT. Mitra Keluarga Karyasehat Tbk',
                'alamat' => 'Jl. Raya Gading Kirana Kav. 2, Jakarta',
                'no_telepon' => '0214585800',
                'email' => 'corsec@mitrakeluarga.com',
                'website' => 'www.mitrakeluarga.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 88,
                'id_admin' => 8,
                'nama' => 'PT. Wijaya Karya Tbk',
                'alamat' => 'Jl. D.I. Panjaitan Kav. 9-10, Jakarta',
                'no_telepon' => '02180679200',
                'email' => 'investor.relations@wika.co.id',
                'website' => 'www.wika.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 89,
                'id_admin' => 9,
                'nama' => 'PT. Waskita Karya Tbk',
                'alamat' => 'Jl. M.T. Haryono Kav. 10, Jakarta',
                'no_telepon' => '0218507608',
                'email' => 'info@waskita.co.id',
                'website' => 'www.waskita.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 90,
                'id_admin' => 10,
                'nama' => 'PT. Adhi Karya Tbk',
                'alamat' => 'Jl. Raya Pasar Minggu KM. 18, Jakarta',
                'no_telepon' => '0217975312',
                'email' => 'adhi@adhi.co.id',
                'website' => 'www.adhi.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 91,
                'id_admin' => 1,
                'nama' => 'PT. Pembangunan Perumahan Tbk',
                'alamat' => 'Plaza PP, Jl. TB. Simatupang No. 57, Jakarta',
                'no_telepon' => '02188638000',
                'email' => 'corsec@ptpp.co.id',
                'website' => 'www.ptpp.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 92,
                'id_admin' => 2,
                'nama' => 'PT. Pakuwon Jati Tbk',
                'alamat' => 'EastCoast Center Lt. 5, Surabaya',
                'no_telepon' => '0315820888',
                'email' => 'info@pakuwon.com',
                'website' => 'www.pakuwon.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 93,
                'id_admin' => 3,
                'nama' => 'PT. Summarecon Agung Tbk',
                'alamat' => 'Plaza Summarecon, Bekasi',
                'no_telepon' => '0214535688',
                'email' => 'corporate.secretary@summarecon.com',
                'website' => 'www.summarecon.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 94,
                'id_admin' => 4,
                'nama' => 'PT. Gudang Garam Tbk',
                'alamat' => 'Jl. Semampir II/1, Kediri',
                'no_telepon' => '0354682091',
                'email' => 'corporate_secretary@gudanggaramtbk.com',
                'website' => 'www.gudanggaramtbk.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 95,
                'id_admin' => 5,
                'nama' => 'PT. HM Sampoerna Tbk',
                'alamat' => 'Jl. Rungkut Industri Raya No. 18, Surabaya',
                'no_telepon' => '0318431699',
                'email' => 'investor.relations@sampoerna.com',
                'website' => 'www.sampoerna.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 96,
                'id_admin' => 6,
                'nama' => 'PT. Bentoel Internasional Investama Tbk',
                'alamat' => 'Jl. Raya Karanglo, Malang',
                'no_telepon' => '0341487000',
                'email' => 'denisyusri_soegiarto@bat.com',
                'website' => 'www.bentoel.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 97,
                'id_admin' => 7,
                'nama' => 'PT. Ultra Jaya Milk Industry Tbk',
                'alamat' => 'Jl. Raya Cimareme No. 131, Bandung',
                'no_telepon' => '0226803888',
                'email' => 'ultrajaya@ultrajaya.co.id',
                'website' => 'www.ultrajaya.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 98,
                'id_admin' => 8,
                'nama' => 'PT. Garudafood Putra Putri Jaya Tbk',
                'alamat' => 'Jl. Bintaro Raya No. 10A, Jakarta',
                'no_telepon' => '02129869888',
                'email' => 'corporate.secretary@garudafood.co.id',
                'website' => 'www.garudafood.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 99,
                'id_admin' => 9,
                'nama' => 'PT. Bisi International Tbk',
                'alamat' => 'Jl. Raya Surabaya-Mojokerto Km. 19, Sidoarjo',
                'no_telepon' => '0318910983',
                'email' => 'info@bisi.co.id',
                'website' => 'www.bisi.co.id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_perusahaan' => 100,
                'id_admin' => 10,
                'nama' => 'PT. Chandra Asri Petrochemical Tbk',
                'alamat' => 'Wisma Barito Pacific Tower A, Jakarta',
                'no_telepon' => '0215304710',
                'email' => 'corporate.comm@capcx.com',
                'website' => 'www.chandra-asri.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('m_perusahaan')->insert($data);

        $this->command->info('Berhasil menyeeder ' . count($data) . ' data perusahaan');
    }
}