<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data untuk Admin (10 user)
        $admins = [
            [
                'id_user' => 1,
                'nama' => 'Admin Satu',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Mawar Satu No. 1',
                'no_telepon' => '081234567890',
                'profile_picture' => 'zzz', 
                'id_role' => 1,
            ],
            [
                'id_user' => 2,
                'nama' => 'Sari Indah',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Ahmad Yani No. 45',
                'no_telepon' => '081234567891',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 3,
                'nama' => 'Bambang Prakoso',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Sudirman Blok C2 No. 7',
                'no_telepon' => '085678912345',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 4,
                'nama' => 'Dewi Safitri',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Griya Indah Blok F No. 12',
                'no_telepon' => '087812345678',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 5,
                'nama' => 'Agus Hermawan',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Gatot Subroto No. 34',
                'no_telepon' => '089876543210',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 6,
                'nama' => 'Ratna Sari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Permata Hijau Blok A3 No. 9',
                'no_telepon' => '081345678901',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 7,
                'nama' => 'Eko Prasetyo',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Cendrawasih No. 56',
                'no_telepon' => '085234567890',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 8,
                'nama' => 'Novi Andini',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Diponegoro No. 78',
                'no_telepon' => '082345678901',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 9,
                'nama' => 'Dian Purnomo',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Bumi Asri Blok D No. 23',
                'no_telepon' => '089012345678',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
            [
                'id_user' => 10,
                'nama' => 'Tia Kusuma',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Veteran No. 67',
                'no_telepon' => '081456789012',
                'profile_picture' => 'zzz',
                'id_role' => 1,
            ],
        ];

        // Data untuk Mahasiswa (70 user)
        $mahasiswa = [
            [
                'id_user' => 11,
                'nama' => 'Cristiano Ronaldo',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Melati No. 2',
                'no_telepon' => '081234567891',
                'profile_picture' => 'zzz', 
                'id_role' => 2,
            ],
            [
                'id_user' => 12,
                'nama' => 'Andi Wijaya',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Pahlawan No. 15',
                'no_telepon' => '082156789012',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 13,
                'nama' => 'Siti Rahayu',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Graha Indah Blok B3 No. 7',
                'no_telepon' => '083167890123',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 14,
                'nama' => 'Budi Santoso',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Mangga No. 24',
                'no_telepon' => '084178901234',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 15,
                'nama' => 'Dina Maulida',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Anggrek No. 37',
                'no_telepon' => '085189012345',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 16,
                'nama' => 'Fajar Nugroho',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Permata Asri Blok C5 No. 12',
                'no_telepon' => '086190123456',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 17,
                'nama' => 'Nita Anggraini',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kenari No. 43',
                'no_telepon' => '087201234567',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 18,
                'nama' => 'Rudi Hartono',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Cempaka No. 19',
                'no_telepon' => '088212345678',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 19,
                'nama' => 'Maya Susanti',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Taman Sari Blok E2 No. 8',
                'no_telepon' => '089223456789',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 20,
                'nama' => 'Irfan Hakim',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Dahlia No. 51',
                'no_telepon' => '081234567892',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 21,
                'nama' => 'Nina Oktavia',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Teratai No. 29',
                'no_telepon' => '082345678903',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 22,
                'nama' => 'Hendra Gunawan',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Bumi Asri Blok F7 No. 15',
                'no_telepon' => '083456789014',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 23,
                'nama' => 'Rina Agustina',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Flamboyan No. 63',
                'no_telepon' => '084567890125',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 24,
                'nama' => 'Dodi Mulyadi',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Delima No. 37',
                'no_telepon' => '085678901236',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 25,
                'nama' => 'Putri Wulandari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Indah Permai Blok D8 No. 21',
                'no_telepon' => '086789012347',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 26,
                'nama' => 'Andri Kurniawan',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Meranti No. 42',
                'no_telepon' => '087890123458',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 27,
                'nama' => 'Yuni Hastuti',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Seruni No. 27',
                'no_telepon' => '088901234569',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 28,
                'nama' => 'Dendi Pratama',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Griya Indah Blok G1 No. 3',
                'no_telepon' => '089012345670',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 29,
                'nama' => 'Lina Marlina',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kenanga No. 54',
                'no_telepon' => '081234567893',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 30,
                'nama' => 'Agung Prabowo',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kemuning No. 31',
                'no_telepon' => '082345678904',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 31,
                'nama' => 'Kartika Sari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Bukit Indah Blok C4 No. 9',
                'no_telepon' => '083456789015',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 32,
                'nama' => 'Joko Susilo',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Cendana No. 47',
                'no_telepon' => '084567890126',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 33,
                'nama' => 'Fitriani',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Beringin No. 22',
                'no_telepon' => '085678901237',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 34,
                'nama' => 'Rizki Ramadhan',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Taman Harapan Blok B6 No. 14',
                'no_telepon' => '086789012348',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 35,
                'nama' => 'Anisa Rahmawati',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Bougenville No. 39',
                'no_telepon' => '087890123459',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 36,
                'nama' => 'Yoga Pratama',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kamboja No. 26',
                'no_telepon' => '088901234570',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 37,
                'nama' => 'Diana Permata',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Citra Garden Blok D5 No. 11',
                'no_telepon' => '089012345681',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 38,
                'nama' => 'Firman Utama',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Belimbing No. 49',
                'no_telepon' => '081234567894',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 39,
                'nama' => 'Rini Anggraeni',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Nangka No. 35',
                'no_telepon' => '082345678905',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 40,
                'nama' => 'Aditya Nugroho',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Graha Asri Blok E3 No. 17',
                'no_telepon' => '083456789016',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 41,
                'nama' => 'Lia Puspita',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Durian No. 53',
                'no_telepon' => '084567890127',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 42,
                'nama' => 'Anton Wijaya',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Salak No. 28',
                'no_telepon' => '085678901238',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 43,
                'nama' => 'Susi Susanti',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Puri Indah Blok F2 No. 19',
                'no_telepon' => '086789012349',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 44,
                'nama' => 'Bayu Setiawan',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kelapa No. 41',
                'no_telepon' => '087890123460',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 45,
                'nama' => 'Dewi Lestari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Rambutan No. 33',
                'no_telepon' => '088901234571',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 46,
                'nama' => 'Hadi Supriyanto',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Bumi Sejahtera Blok C7 No. 23',
                'no_telepon' => '089012345682',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 47,
                'nama' => 'Wulan Sari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Semangka No. 57',
                'no_telepon' => '081234567895',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 48,
                'nama' => 'Arif Rahman',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Pepaya No. 36',
                'no_telepon' => '082345678906',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 49,
                'nama' => 'Eka Putri',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Griya Alam Blok D4 No. 13',
                'no_telepon' => '083456789017',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 50,
                'nama' => 'Dani Firmansyah',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Pisang No. 44',
                'no_telepon' => '084567890128',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 51,
                'nama' => 'Tina Agustina',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Jeruk No. 25',
                'no_telepon' => '085678901239',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 52,
                'nama' => 'Reza Mahendra',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Taman Sari Blok G3 No. 18',
                'no_telepon' => '086789012350',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 53,
                'nama' => 'Ika Yulianti',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Apel No. 38',
                'no_telepon' => '087890123461',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 54,
                'nama' => 'Dika Saputra',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kiwi No. 29',
                'no_telepon' => '088901234572',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 55,
                'nama' => 'Nia Kurniati',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Pesona Indah Blok E6 No. 24',
                'no_telepon' => '089012345683',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 56,
                'nama' => 'Adi Wicaksono',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Manggis No. 52',
                'no_telepon' => '081234567896',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 57,
                'nama' => 'Yanti Susilo',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Sirsak No. 34',
                'no_telepon' => '082345678907',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 58,
                'nama' => 'Yusuf Ibrahim',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Graha Persada Blok F4 No. 16',
                'no_telepon' => '083456789018',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 59,
                'nama' => 'Erni Susilowati',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Jambu No. 46',
                'no_telepon' => '084567890129',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 60,
                'nama' => 'Imam Hidayat',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Markisa No. 27',
                'no_telepon' => '085678901240',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 61,
                'nama' => 'Fani Wulandari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Citra Garden Blok G5 No. 22',
                'no_telepon' => '086789012351',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 62,
                'nama' => 'Agus Pranoto',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Sawo No. 42',
                'no_telepon' => '087890123462',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 63,
                'nama' => 'Evi Sulastri',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Sukun No. 31',
                'no_telepon' => '088901234573',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 64,
                'nama' => 'Taufik Hidayat',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Taman Asri Blok B8 No. 27',
                'no_telepon' => '089012345684',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 65,
                'nama' => 'Laras Ayu',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Nanas No. 55',
                'no_telepon' => '081234567897',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 66,
                'nama' => 'Rian Saputra',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Duku No. 32',
                'no_telepon' => '082345678908',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 67,
                'nama' => 'Novi Rahmawati',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Bumi Indah Blok C9 No. 21',
                'no_telepon' => '083456789019',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 68,
                'nama' => 'Iwan Setiawan',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Mangga Dua No. 48',
                'no_telepon' => '084567890130',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 69,
                'nama' => 'Lina Wati',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kedondong No. 30',
                'no_telepon' => '085678901241',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 70,
                'nama' => 'Rudi Hartanto',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Permata Indah Blok D7 No. 19',
                'no_telepon' => '086789012352',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 71,
                'nama' => 'Rika Fitriani',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Langsat No. 40',
                'no_telepon' => '087890123463',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 72,
                'nama' => 'Doddy Ferdiansyah',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Leci No. 25',
                'no_telepon' => '088901234574',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 73,
                'nama' => 'Vera Sulistiawati',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Griya Husada Blok F8 No. 15',
                'no_telepon' => '089012345685',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 74,
                'nama' => 'Galih Prabowo',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Cermai No. 59',
                'no_telepon' => '081234567898',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 75,
                'nama' => 'Desi Ratnasari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Srikaya No. 37',
                'no_telepon' => '082345678909',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 76,
                'nama' => 'Farid Abdullah',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Taman Permata Blok E7 No. 20',
                'no_telepon' => '083456789020',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 77,
                'nama' => 'Rita Handayani',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Alpukat No. 45',
                'no_telepon' => '084567890131',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 78,
                'nama' => 'Hendri Cahyono',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Melon No. 28',
                'no_telepon' => '085678901242',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 79,
                'nama' => 'Mira Lestari',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Puri Harmoni Blok B9 No. 25',
                'no_telepon' => '086789012353',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
            [
                'id_user' => 80,
                'nama' => 'Wahyu Hidayat',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Anggur No. 51',
                'no_telepon' => '087890123464',
                'profile_picture' => 'zzz',
                'id_role' => 2,
            ],
        ];

        // Data untuk Dosen Pembimbing (20 user)
        $dosenPembimbing = [
            [
                'id_user' => 81,
                'nama' => 'Budi Santoso, S.Kom, M.Kom',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kenanga No. 3',
                'no_telepon' => '081234567892',
                'profile_picture' => 'zzz', 
                'id_role' => 3,
            ],
            [
                'id_user' => 82,
                'nama' => 'Dr. Ahmad Fauzi, S.T., M.Sc.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Menteng No. 45',
                'no_telepon' => '082345678910',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 83,
                'nama' => 'Prof. Dr. Sri Mulyani, M.Si.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Dosen Blok A No. 12',
                'no_telepon' => '083456789021',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 84,
                'nama' => 'Ir. Dedi Supriyadi, M.T.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Cendrawasih No. 28',
                'no_telepon' => '084567890132',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 85,
                'nama' => 'Dr. Rina Wahyuni, S.Kom., M.M.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Elite Blok B No. 7',
                'no_telepon' => '085678901243',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 86,
                'nama' => 'Dr. Hendro Purnomo, S.T., M.Eng.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Garuda No. 19',
                'no_telepon' => '086789012354',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 87,
                'nama' => 'Dr. Lia Amalia, M.Pd.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Rajawali No. 33',
                'no_telepon' => '087890123465',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 88,
                'nama' => 'Prof. Dr. Agus Susanto, M.Cs.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Permata Hijau Blok D No. 15',
                'no_telepon' => '088901234576',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 89,
                'nama' => 'Dr. Nina Wachidah, S.Si., M.Kom.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Merpati No. 27',
                'no_telepon' => '089012345687',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 90,
                'nama' => 'Ir. Bambang Widodo, M.T.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Griya Ilmu Blok C No. 9',
                'no_telepon' => '081234567899',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 91,
                'nama' => 'Dr. Siti Fatimah, S.Kom., M.Si.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Elang No. 42',
                'no_telepon' => '082345678911',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 92,
                'nama' => 'Dr. Joko Sutrisno, M.Eng.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Kakatua No. 31',
                'no_telepon' => '083456789022',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 93,
                'nama' => 'Prof. Dr. Dewi Kartika, S.T., M.Sc.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Dosen Blok E No. 18',
                'no_telepon' => '084567890133',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 94,
                'nama' => 'Dr. Eko Prasetyo, S.Si., M.Kom.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Cenderawasih No. 24',
                'no_telepon' => '085678901244',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 95,
                'nama' => 'Dr. Ratna Sari, S.E., M.M.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Taman Ilmu Blok F No. 11',
                'no_telepon' => '086789012355',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 96,
                'nama' => 'Prof. Dr. Hadi Wijaya, M.T.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Merak No. 37',
                'no_telepon' => '087890123466',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 97,
                'nama' => 'Dr. Yanti Lusiana, S.Pd., M.Si.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Perkutut No. 29',
                'no_telepon' => '088901234577',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 98,
                'nama' => 'Dr. Yusuf Hamdani, S.T., M.Cs.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Komplek Griya Cendekia Blok G No. 21',
                'no_telepon' => '089012345688',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 99,
                'nama' => 'Prof. Dr. Anita Rahmawati, M.Kom.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Jl. Jalak No. 47',
                'no_telepon' => '081234567800',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
            [
                'id_user' => 100,
                'nama' => 'Dr. Hendra Kusuma, S.Kom., M.T.',
                'password' => bcrypt('12345678'),
                'alamat' => 'Perumahan Bumi Akademisi Blok D No. 23',
                'no_telepon' => '082345678912',
                'profile_picture' => 'zzz',
                'id_role' => 3,
            ],
        ];

        // Gabungkan semua data
        $allUsers = array_merge($admins, $mahasiswa, $dosenPembimbing);

        DB::table('m_user')->insert($allUsers);
    }
}